### ISSUE TITLE
[android] Can't see any "available data sources"

### ISSUE THREAD

**Issue by ahjolinna** [omnight/phonehook#28]
I just installed phonehook on my Xperia Z3+ using android 7.0, and everytime I open it I get a pop that says I should add some data sources to get started, and I press "okay" I just get an empty "available sources" page everytime

_I should also add that I use Telia (just changed their name from Sonera) and I live in Finland...if this info matters_

ps. I loved this app when I use it on my Jolla phone, I hope I can use sailfishOS again when the Xperia X phones arrives with SailfishOS

**Comment by omnight** [comment]
Hi!

There is currently an issue with Android 7 that causes the app not to be able to establish SSL connections (so it can't download anything from https), I have a fix in the works, but running the app in the emulator causes a crash, even though it seems to work ok with my Android 6.0 test phone. If you are interested in trying out an alpha apk-file (which may or may not work) I can send it to you.

**Comment by ahjolinna** [comment]
@omnight : well that sucks, but then again many phone manufacturers are really slow to update android if they even bother, so this wont be a problem for many... anyway sure I can test the alpha build, sounds like fun

PS. have you heard about [clazy](http://phoronix.com/scan.php?page=news_item&px=Clang-Clazy-Qt-Slow-Mistakes)?  it checks for "inefficient Qt coding mistakes"

**Comment by omnight** [comment]
I might have to delay that alpha build a bit, did some more testing and it seems the SSL-lib changes are causing new crashes. The problem is that Android 7 doesn't ship with SSL binaries that Qt can use, and Qt does not include any due to licensing issues, so now you have to compile your own.

I haven't heard about clazy, but I will check it out once my app is actually working again :)

**Comment by ahjolinna** [comment]
any progress yet?...

(btw. Qt 5.9 will be the next LTS release and it will arrive 31st May 2017) ...are you going to use v5.9 for android version?

PS. when you are trying clazy, it has problems with Qt5.8 at least on windows : [bug report](https://bugreports.qt.io/browse/QTBUG-59190)

**Comment by ahjolinna** [comment]
well that suck...anyway have you only tried that on emulator and not on[ actual device](https://developer.android.com/studio/run/device.html)? it also good to check [the documents about testing](https://developer.android.com/training/testing/index.html) if u haven't already

also, I did try that apk on my phone and it said that the file was corrupted.

------

I really hope the Sony Xperia X sailfishOS phone will arrive soon so I don't need to use android anymore.

**Comment by omnight** [comment]
Sorry, may have mixed up the files, here is another attempt

[phonehook_android7_test2.zip](https://github.com/omnight/phonehook/files/989991/phonehook_android7_test2.zip)

I have tested this one on my Android 6 phone and in the half-broken Android 7 emulator.

**Comment by ahjolinna** [comment]
that wasnt any better at all, do u think Qt5.9 could help? ...I know that 5.8 was really broken release

**Comment by omnight** [comment]
The latest one is built with 5.9 beta 3, but it has a debug signature, so you will need to uninstall any Google Play version of the app and also enable "install from unknown sources" in settings.

Are you still getting errors while doing that?

**Comment by ahjolinna** [comment]
I forgot to remove the play store version, anyway it works now.. At least I can see the "list"... 

One thing I noticed is that "fonecta app" says that I have to old phonehook version... Fonecta.fi works/opens...but login doesn't work 

Fonecta doesn't use phone number as the username anymore it's now email address... And/or Facebook/Google account is also supported 
https://tili.fonecta.fi/login#/

**Comment by omnight** [comment]
Yeah, the Android version is a bit behind the Sailfish version, I'll try to get it up to speed. Anyway, good thing that you can see the list now, that was my biggest issue.

**Comment by ahjolinna** [comment]
fonecta app "works"  now but not the login...nothing happens when I try to login

unfortunately their documentation is in finnish (only?) https://api.fonecta.fi/api-docs/yhteystieto-api

**Comment by omnight** [comment]
The login is actually made when a lookup is performed, so try using the test function to look up a number after entering your login details.

**Comment by ahjolinna** [comment]
okay login seems to work ...maybe... not 100% sure...that sucks that there isnt any "login indicator".....and yes I tested the "test function" and search in general...and no luck with it

**Comment by ahjolinna** [comment]
okay now it works? wtf? :D

**Comment by omnight** [comment]
I tested the "Search" function now with Fonecta, and that didn't work so well for me (app crashed), will look into it next week.

**Comment by ahjolinna** [comment]
well it worked for me at least once now...I didnt have the crash issue....btw. the "home" and "settings" thing don't do anything either

**Comment by omnight** [comment]
Yeah, I probably messed up some code that prevents the settings page from loading. It's getting there! :)

**Comment by ahjolinna** [comment]
well baby steps... and there is no hurry at least until Qt5.9 has been released

**Comment by omnight** [comment]
I've fixed the bugs that I found, and also updated the Fonecta App source to better handle search.

New version: 
[phonehook_android7_test4.zip](https://github.com/omnight/phonehook/files/1003863/phonehook_android7_test4.zip)

**Comment by ahjolinna** [comment]
seems to work little bit better ...cant say that much about the search yet, at least the "home button/page" works now, but settings one is still broken...if you try from the "home page" nothings happens...and from other "pages" it just goes to an blank page

**Comment by omnight** [comment]
Interestingly, the settings page works fine on Android 5, but crashes on Android 6/7, seems to be related to this issue: https://bugreports.qt.io/browse/QTBUG-59026

Qt 5.9 got a new release yesterday, so I'm going to try that out.

**Comment by ahjolinna** [comment]
yeah it also seems qt5.9 stable release will be little bit late..the RC1 was meant to arrive the [17th may](http://lists.qt-project.org/pipermail/announce/2017-May/000114.html) but it will  now arrive next week instead...anyway did you try out the [clazy](https://github.com/KDE/clazy) thing with 5.9(beta)

**Comment by omnight** [comment]
Here's a new version built with 5.9 beta 4, also added a few minor features that the Sailfish version has.

[phonehook_android7_test5.zip](https://github.com/omnight/phonehook/files/1007058/phonehook_android7_test5.zip)

I had a look at clazy and it looks very useful, but not sure I can use it with the current Android-only setup I have, since it uses gcc instead of clang.

**Comment by ahjolinna** [comment]
cool, the settings page works now at least...will test it more soon...anyway...
nowdays I'm personally all for using clang instead of gcc ...also: 

[Android NDK: GCC is now deprecated, everyone should be switching to Clang ](https://news.ycombinator.com/item?id=10772826)

and https://developer.android.com/ndk/guides/standalone_toolchain.html#working_with_clang

**Comment by ahjolinna** [comment]
the "test number" (fonecta app) doesnt seem to work yet, I do get a popup but it says that it cant find the number...but when I go to normal search it finds it just fine.

(I tested my own phone number)

**Comment by omnight** [comment]
Might be some issue after first login. Does it work if you clear the cache and test the number again?

**Comment by ahjolinna** [comment]
clearing the cache made it worse...now "test number" doesn't work at all :D

**Comment by omnight** [comment]
Did you use the in-app "Clear Cache" option for the source, or the android clear cache feature? I realize now that I wasn't too specific.

I'll run some more tests here and see if I can reproduce the issue.

**Comment by ahjolinna** [comment]
in-app "Clear Cache" option

**Comment by omnight** [comment]
I've made another update to the Fonecta App source, it seems that the fields returned from the server can vary a bit (haven't figured out why yet) which caused the response parsing to fail.

**Comment by ahjolinna** [comment]
didnt work yet

**Comment by omnight** [comment]
Even after clearing? It works for me now, so don't know what the problem is this time

**Comment by ahjolinna** [comment]
it seems 2nd try is the charm, at least after running [simpli clean](https://play.google.com/store/apps/details?id=com.simplitec.simplitecapp) (F-secure booster was based on this) ...and the in-app "Clear Cache" option

**Comment by omnight** [comment]
So even if you delete/re-install the app it still only works on the 2nd try? If you can provide adb logs to me (just scrub sensitive information) I might be able to see what's going on.

I'm actually not sure how to change over to clang. It seems that Qt has added support for clang, but they still build with gcc because the libs are too big when compiling with clang. https://bugreports.qt.io/browse/QTBUG-50724

**Comment by ahjolinna** [comment]
it seems to work now...I'm not sure why it didn't at first...
anyway I haven't found any doc/status report about building android apps with clang with v5.9...have to wait for the actual release....as qt has been moving towards clang, but hasn't made it default yet for android

**Comment by omnight** [comment]
Since Qt 5.9 has been released properly now, I've built a new version of Phonehook linking with Qt 5.9. 

I also noticed that I had accidentally been working from an earlier commit for the earlier test versions I put up here, so several of the issues are actually already fixed in the live Google Play version. I've done an attempt to merge everything, so now a bit more stuff should be working (like the Truecaller App source).

[phonehook_android7_test6.zip](https://github.com/omnight/phonehook/files/1044525/phonehook_android7_test6.zip)

**Comment by ahjolinna** [comment]
sorry for the late reply, anyway I just tested it and everything seems to work, oc I have some other gripes with it ...mostly with UI/UX...I will maybe do another bug report about that (I doubt it as I only care about sailfishOS version soon)

so anyways closing this..

----------

if you are intrested to do something about the android UI, I would maybe check the KDE's  Kirigami (guidelines) project https://techbase.kde.org/Kirigami
